Q0:
  XY: {chassis: 1, slot: 4, channel: 1}
  RO: {chassis: 1, slot: 8, channel: 1}
  DNC: {chassis: 1, slot: 17, channel: 2}
  DIG: {chassis: 1, slot: 18, channel: 2}

Q1:
  XY: {chassis: 1, slot: 4, channel: 2}
  RO: {chassis: 1, slot: 8, channel: 1}
  DNC: {chassis: 1, slot: 17, channel: 2}
  DIG: {chassis: 1, slot: 18, channel: 2}

Q2:
  XY: {chassis: 1, slot: 4, channel: 3}
  RO: {chassis: 1, slot: 8, channel: 1}
  DNC: {chassis: 1, slot: 17, channel: 2}
  DIG: {chassis: 1, slot: 18, channel: 2}